---
- name: Run mysql
  docker_container:
    name: mysql
    restart_policy: always
    image: mariadb:10
    restart: "{{ mysql_restart |  default(false) }}"
    env:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_USER: "{{ nextcloud_db_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_db_pass }}"
      MYSQL_DATABASE: "{{ nextcloud_db_name }}"
    volumes:
      - "{{ nextcloud_data_dir_mysql }}:/var/lib/mysql"
    log_driver: "{{ nextcloud_log_driver | default(omit) }}"
    log_options: "{{ nextcloud_log_options | default(omit) }}"
  tags:
    - mysql

- name: Run nextcloud
  docker_container:
    name: nextcloud
    restart_policy: always
    image: "nextcloud:{{ nextcloud_version }}-apache"
    restart: "{{ nextcloud_restart |  default(false) }}"
    env:
      MYSQL_HOST: "{{ nextcloud_db_host }}"
      MYSQL_USER: "{{ nextcloud_db_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_db_pass }}"
      MYSQL_DATABASE: "{{ nextcloud_db_name }}"
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TABLE_PREFIX: "{{ nextcloud_table_prefix }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_trusted_domains }}"
    ports: "{{ nextcloud_ports |  default(false) }}"
    volumes:
      - "{{ nextcloud_data_dir_nextcloud }}:/var/www/html/data"
    links:
      - mysql
    log_driver: "{{ nextcloud_log_driver | default(omit) }}"
    log_options: "{{ nextcloud_log_options | default(omit) }}"
  tags:
    - nextcloud
