---
- name: Converge
  become: true
  become_method: sudo
  hosts: all
  vars:
    nextcloud_trusted_domains: http://192.168.56.20:10080
  roles:
    - { role: ansible-role-nextcloud, tags: ['ansible-role-nextcloud'] }
