---
- name: Converge
  hosts: all
  vars:
    molecule_scenario_no_deps: true
    nextcloud_trusted_domains: http://192.168.56.20:10080
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - { role: ansible-role-docker-nextcloud, tags: ['nextcloud'] }
